name: CI

on:
  pull_request:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Set up Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v4
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Lint
        run: npm run lint

      - name: Frontend tests
        run: npm test

      - name: Frontend coverage
        run: npm run test:coverage

      - name: Coverage upload
        uses: codecov/codecov-action@v3

      - name: Frontend build
        run: npm run build

      - name: Server tests
        run: npm --prefix server test

      - name: Security scan
        run: npm audit --audit-level=high
